# Generated by Django 4.0.4 on 2022-05-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
