# Generated by Django 4.0.4 on 2022-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
