# Generated by Django 4.0.4 on 2022-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_cart_quantity_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=3, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
