# Generated by Django 4.0.4 on 2022-05-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_order_address_order_phone_alter_order_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
