# Generated by Django 4.0.4 on 2022-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_rename_address_order_address_remove_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
