# Generated by Django 4.0.4 on 2022-05-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
